# Generated by Django 5.0.6 on 2024-10-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("przychody", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="przychod",
            options={"verbose_name": "Przychód", "verbose_name_plural": "Przychody"},
        ),
    ]
