# Generated by Django 5.0.6 on 2025-02-08 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.PositiveIntegerField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_processed", models.IntegerField(default=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_category", models.CharField(max_length=100)),
                ("product_unit", models.CharField(max_length=50)),
                (
                    "product_purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("product_supplier", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_id", models.PositiveIntegerField()),
                ("table_id", models.PositiveIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesTransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("product_name", models.CharField(max_length=100)),
                ("product_category", models.CharField(max_length=100)),
                ("product_unit", models.CharField(max_length=50)),
                (
                    "product_purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_supplier", models.CharField(max_length=100)),
                (
                    "sales_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dashboard.salestransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("is_reserved", models.BooleanField(default=False)),
                ("reserved_for", models.DateTimeField(blank=True, null=True)),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True, related_name="tables", to="dashboard.orderedproduct"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.table"
            ),
        ),
    ]
