# Generated by Django 5.0.6 on 2024-10-27 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

def create_initial_data(apps, schema_editor):
    # Pobierz modele
    ItemCategory = apps.get_model('inventory', 'ItemCategory')
    Supplier = apps.get_model('inventory', 'Supplier')
    UnitOfMeasurement = apps.get_model('inventory', 'UnitOfMeasurement')

    # Dodaj kategorie produktów
    ItemCategory.objects.bulk_create([
        ItemCategory(name='Sypkie'),
        ItemCategory(name='Mięso'),
        ItemCategory(name='Nabiał'),
        ItemCategory(name='Warzywa'),
        ItemCategory(name='Napoje'),
        ItemCategory(name='Przyprawy'),
        ItemCategory(name='Nieznana'),
    ])

    # Dodaj dostawców z nowymi danymi
    Supplier.objects.bulk_create([
        Supplier(
            name='Dostawca A',
            address='ul. Przykładowa 1, 00-001 Warszawa',
            phone='123456789',
            email='dostawcaA@example.com',
        ),
        Supplier(
            name='Dostawca B',
            address='ul. Testowa 2, 00-002 Kraków',
            phone='987654321',
            email='dostawcaB@example.com',
        ),
        Supplier(
            name='Dostawca C',
            address='ul. Nowa 3, 00-003 Wrocław',
            phone='456789123',
            email='dostawcaC@example.com',
        ),
    ])

    # Dodaj jednostki miary
    UnitOfMeasurement.objects.bulk_create([
        UnitOfMeasurement(name='kg'),
        UnitOfMeasurement(name='szt'),
        UnitOfMeasurement(name='op'),
        UnitOfMeasurement(name='l'),
        UnitOfMeasurement(name='Nieznana'),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expiration_date', models.DateField(default='1000-01-01')),
                ('last_restock_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemcategory'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasurement'),
        ),

        migrations.RunPython(create_initial_data),
    ]
