# Generated by Django 5.0.6 on 2024-10-23 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='threshold',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('dry', 'Sypkie'), ('meat', 'Mięso'), ('dairy', 'Nabiał'), ('vegetable', 'Warzywa'), ('beverage', 'Napoje'), ('spice', 'Przyprawy'), ('unknown', 'Nieznana')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_restock_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(default='Nieznany', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('kilogramy', 'kg'), ('sztuki', 'szt'), ('opakowania', 'op'), ('litry', 'l'), ('unknown', 'Nieznana')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
