# Generated by Django 5.0.6 on 2024-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Sypkie', 'Sypkie'), ('Mięso', 'Mięso'), ('Nabiał', 'Nabiał'), ('Warzywa', 'Warzywa'), ('Napoje', 'Napoje'), ('Przyprawy', 'Przyprawy'), ('Nieznana', 'Nieznana')], default='Nieznana', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('szt', 'szt'), ('op', 'op'), ('l', 'l'), ('Nieznana', 'Nieznana')], default='Nieznana', max_length=20),
        ),
    ]
