# Generated by Django 5.0.6 on 2025-01-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_merge_20250124_0025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
